FROM {{ base_image_name }}

{%- import 'macros.j2' as macros -%}

{%- if files['binaries']['.tar.gz'] -%}
{% set binaries_build_args -%}
ARG APACHE_MAVEN_BINARIES_URL="{{ files['binaries']['.tar.gz']['url'] }}"
ARG APACHE_MAVEN_BINARIES="{{ files['binaries']['.tar.gz']['filename'] }}"
{%- endset %}
{%- if files['binaries']['.tar.gz']['signature'] -%}
{% set signature_build_args -%}
ARG APACHE_MAVEN_GPG_KEYS_URL=http://www-eu.apache.org/dist/maven/KEYS
ARG APACHE_MAVEN_GPG_KEYS=KEYS
ARG APACHE_MAVEN_SIGNATURE_URL="{{ files['binaries']['.tar.gz']['signature']['url'] }}"
ARG APACHE_MAVEN_SIGNATURE="{{ files['binaries']['.tar.gz']['signature']['filename'] }}"
{%- endset %}
{% set download_and_verify_signature -%}
{{ macros.curl('${APACHE_MAVEN_GPG_KEYS_URL}', '${APACHE_MAVEN_GPG_KEYS}') }} && \
{{ macros.curl('${APACHE_MAVEN_SIGNATURE_URL}', '${APACHE_MAVEN_SIGNATURE}') }} && \
{{ macros.import_gpg_key_file('${APACHE_MAVEN_GPG_KEYS}') }} && \
{{ macros.curl('${APACHE_MAVEN_SIGNATURE_URL}', '${APACHE_MAVEN_SIGNATURE}') }} && \
{{ macros.gpg_verify('${APACHE_MAVEN_SIGNATURE}') }} && \
{%- endset %}
{%- endif -%}
{%- endif -%}

ARG VENDOR=apache
ARG PRODUCT=maven
ARG PRODUCT_VERSION={{ version }}
ARG TEMP_DIR_ROOT=/tmp/${VENDOR}-${PRODUCT}
ARG TEMP_DIR=/${TEMP_DIR_ROOT}/${PRODUCT_VERSION}
ARG INSTALL_DIR_ROOT=/opt/${VENDOR}-${PRODUCT}
ARG INSTALL_DIR=${INSTALL_DIR_ROOT}/${PRODUCT_VERSION}

{% if binaries_build_args -%}
{{ binaries_build_args }}
{%- endif %}
{% if signature_build_args -%}
{{ signature_build_args }}
{%- endif %}

USER ${ROOT_UID}

RUN \
mkdir -p ${TEMP_DIR} ${INSTALL_DIR} && \
cd ${TEMP_DIR} && \
{% if binaries_build_args -%}
{{ macros.curl('${APACHE_MAVEN_BINARIES_URL}', '${APACHE_MAVEN_BINARIES}') }} && \
{% if download_and_verify_signature -%}
{{ download_and_verify_signature }}
{%- endif %}
{{ macros.extract_tarball('${APACHE_MAVEN_BINARIES}', '${INSTALL_DIR}') }} && \
{%- endif %}
fix-ownership ${INSTALL_DIR} && \
fix-permissions ${INSTALL_DIR} && \
rm -rf ${TEMP_DIR_ROOT}

ENV M2_HOME ${INSTALL_DIR}
ENV PATH ${M2_HOME}/bin:${PATH}

USER ${APP_UID}

